name = "danogo-finance/stdlib"
version = "main"
compiler = "v1.1.21"
plutus = "v3"
description = "The Aiken Standard Library"

[repository]
user = "danogo-finance"
project = "stdlib"
platform = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.1.1"
source = "github"
